### ISSUE TITLE
Data files

### ISSUE THREAD

**Issue by artemkolmykov** [vevurka/mt-experiments#2]
Hello.
Perhaps you could help me.
Please tell me where can I  find source data files for the codes?

**Comment by vevurka** [comment]
Unfortunately the data is not public and I don't have permissions to share it. This repository was one of attachments to my master thesis. I used the data provided by my university. They bought data from here: http://2015.eurofidai.org/en/accueil_en.html

**Comment by artemkolmykov** [comment]
I see.Thank for your answer.Perhaps to avoid further questions from others you should write it on the readme file.
Anyway I've managed to find in your code what is format of data expected to be.  So thank you for your work.

**Comment by vevurka** [comment]
Ok, I've added very brief info to the README. Thanks for the advise!
